name: CI

on: [push]

jobs:
 codeql_analysis:
   name: CodeQL
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: 3.8

   - name: Init CodeQL
     uses: github/codeql-action/init@v1

   - name: Exec CodeQL Analysis
     run: github/codeql-action/analyze@v1
