name: CI

on: [push]

jobs:
 sast_scan:
   name: Run CodeQL Scan
   runs-on: ubuntu-latest
   timeout-minutes: 360
   permissions:
      security-events: write

   strategy:
     fail-fast: false
     matrix:
       language: [ 'python' ]

   steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Initialize CodeQL
     uses: github/codeql-action/init@v3
     with:
       languages: ${{ matrix.language }}

   - name: Perform CodeQL Analysis
     uses: github/codeql-action/analyze@v3
     with:
       category: "/language:${{matrix.language}}"

 dast_scan:
   runs-on: ubuntu-latest
   name: Scan the web application
   steps:
     - name: ZAP Scan
       uses: zaproxy/action-baseline@v0.6.1
       with:
         docker_name: 'owasp/zap2docker-stable'
         target: 'http://testphp.vulnweb.com/'
         rules_file_name: '.zap/rules.tsv'
         cmd_options: '-a'
         
 dependency-scan:
   runs-on: ubuntu-latest
   steps:
     - name: Dependency Scanning
       uses: actions/dependency-review-action@v4.1.3
       with:
         fail-on-severity: high
         fail-on-scopes: runtime
         vulnerability-check: true
         license-check: true
         
         
         
