name: CI

on: [push]

jobs:
 sast_scan:
   name: Run CodeQL Scan
   runs-on: ubuntu-latest
   timeout-minutes: 360
   permissions:
      security-events: write

   strategy:
     fail-fast: false
     matrix:
       language: [ 'python' ]

   steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Initialize CodeQL
     uses: github/codeql-action/init@v3
     with:
       languages: ${{ matrix.language }}

   - name: Perform CodeQL Analysis
     uses: github/codeql-action/analyze@v3
     with:
       category: "/language:${{matrix.language}}"
